# Generated by Django 3.2 on 2021-04-23 08:46

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('content', models.TextField()),
            ],
        ),
    ]
